export const Users = [
  {
    id: 1,
    profilePicture: "./assets/images/img_1.jpg",
    username: "Dang Nhat Minh 1",
  },
  {
    id: 2,
    profilePicture: "./assets/images/img_12.jpg",
    username: "Dang Nhat Minh 2",
  },
  {
    id: 3,
    profilePicture: "./assets/images/img_3.jpg",
    username: "Dang Nhat Minh 3",
  },
  {
    id: 4,
    profilePicture: "./assets/images/img_4.jpg",
    username: "Dang Nhat Minh 4",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/posts/img_1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/posts/img_2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/posts/img_3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/posts/img_4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/posts/img_5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/posts/img_6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  //   {
  //     id: 7,
  //     desc: "Never regret anything that made you smile.",
  //     photo: "assets/posts/img_7.jpg",
  //     date: "2 days ago",
  //     userId: 7,
  //     like: 52,
  //     comment: 3,
  //   },
  //   {
  //     id: 8,
  //     photo: "assets/posts/8.jpg",
  //     date: "3 days ago",
  //     userId: 8,
  //     like: 15,
  //     comment: 1,
  //   },
  //   {
  //     id: 9,
  //     desc: "Change the world by being yourself.",
  //     photo: "assets/posts/9.jpg",
  //     date: "5 days ago",
  //     userId: 9,
  //     like: 11,
  //     comment: 2,
  //   },
  //   {
  //     id: 10,
  //     photo: "assets/posts/10.jpg",
  //     date: "1 week ago",
  //     userId: 10,
  //     like: 104,
  //     comment: 12,
  //   },
];
